services:
    database:
        container_name: service-hub-db
        image: postgres
        env_file:
            - ./docker/database/.env
        restart: always
        ports:
            - "5432:5432"
        volumes:
            - database-data:/var/lib/postgresql/data/
            - ./docker/database/multiple-databases.sh:/docker-entrypoint-initdb.d/multiple-databases.sh
        networks:
            - service-hub-ext-network

    redis:
        container_name: service-hub-redis
        image: redis:latest
        restart: always
        ports:
            - "6379:6379"
        networks:
            - service-hub-ext-network

volumes:
    database-data: ~
